<a href="https://colab.research.google.com/github/ksh001/py_study/blob/main/py_Study_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/data.csv', encoding='cp949')

In [3]:
df.head()

지역명               규모구분    연도   월 분양가격(㎡)
0  서울                 전체  2015  10    5841
1  서울         전용면적 60㎡이하  2015  10    5652
2  서울   전용면적 60㎡초과 85㎡이하  2015  10    5882
3  서울  전용면적 85㎡초과 102㎡이하  2015  10    5721
4  서울        전용면적 102㎡초과  2015  10    5879

## 4. iloc을 활용한 인덱스 지정 선택

In [4]:
df.iloc[2, 1]

'전용면적 60㎡초과 85㎡이하'

In [5]:
df.iat[2, 1]

'전용면적 60㎡초과 85㎡이하'

In [6]:
df.iloc[2, :]

지역명                      서울
규모구분       전용면적 60㎡초과 85㎡이하
연도                     2015
월                        10
분양가격(㎡)                5882
Name: 2, dtype: object

In [7]:
df.iloc[:5, 1]

0                   전체
1           전용면적 60㎡이하
2     전용면적 60㎡초과 85㎡이하
3    전용면적 85㎡초과 102㎡이하
4          전용면적 102㎡초과
Name: 규모구분, dtype: object

In [9]:
df.iloc[:5, 1:3]

규모구분    연도
0                 전체  2015
1         전용면적 60㎡이하  2015
2   전용면적 60㎡초과 85㎡이하  2015
3  전용면적 85㎡초과 102㎡이하  2015
4        전용면적 102㎡초과  2015

In [11]:
df[df.index > 3565]

지역명               규모구분    연도  월 분양가격(㎡)
3566  제주         전용면적 60㎡이하  2019  3    3804
3567  제주   전용면적 60㎡초과 85㎡이하  2019  3    3504
3568  제주  전용면적 85㎡초과 102㎡이하  2019  3    3226
3569  제주        전용면적 102㎡초과  2019  3    2952
3570  서울                 전체  2019  4    7784
...   ..                ...   ... ..     ...
4585  제주                 전체  2020  3    3955
4586  제주         전용면적 60㎡이하  2020  3    4039
4587  제주   전용면적 60㎡초과 85㎡이하  2020  3    3962
4588  제주  전용면적 85㎡초과 102㎡이하  2020  3     NaN
4589  제주        전용면적 102㎡초과  2020  3    3601

[1024 rows x 5 columns]

In [12]:
df[df.연도 == 2019][:5]

지역명               규모구분    연도  월 분양가격(㎡)
3315  서울                 전체  2019  1    7600
3316  서울         전용면적 60㎡이하  2019  1    7400
3317  서울   전용면적 60㎡초과 85㎡이하  2019  1    8105
3318  서울  전용면적 85㎡초과 102㎡이하  2019  1    6842
3319  서울        전용면적 102㎡초과  2019  1    7787

In [13]:
df[df['연도'] == 2019][:5]

지역명               규모구분    연도  월 분양가격(㎡)
3315  서울                 전체  2019  1    7600
3316  서울         전용면적 60㎡이하  2019  1    7400
3317  서울   전용면적 60㎡초과 85㎡이하  2019  1    8105
3318  서울  전용면적 85㎡초과 102㎡이하  2019  1    6842
3319  서울        전용면적 102㎡초과  2019  1    7787

In [ ]:
df['a'] == df.a

In [14]:
df.head()

지역명               규모구분    연도   월 분양가격(㎡)
0  서울                 전체  2015  10    5841
1  서울         전용면적 60㎡이하  2015  10    5652
2  서울   전용면적 60㎡초과 85㎡이하  2015  10    5882
3  서울  전용면적 85㎡초과 102㎡이하  2015  10    5721
4  서울        전용면적 102㎡초과  2015  10    5879

In [17]:
copy = df.copy()
copy.head()

지역명               규모구분    연도   월 분양가격(㎡)
0  서울                 전체  2015  10    5841
1  서울         전용면적 60㎡이하  2015  10    5652
2  서울   전용면적 60㎡초과 85㎡이하  2015  10    5882
3  서울  전용면적 85㎡초과 102㎡이하  2015  10    5721
4  서울        전용면적 102㎡초과  2015  10    5879

In [18]:
df.loc[df['지역명']=='서울','지역명'][:10]

0     서울
1     서울
2     서울
3     서울
4     서울
85    서울
86    서울
87    서울
88    서울
89    서울
Name: 지역명, dtype: object

In [21]:
df.loc[df['지역명']=='서울','지역명'] = 'Seoul'
df.head()

지역명               규모구분    연도   월 분양가격(㎡)
0  Seoul                 전체  2015  10    5841
1  Seoul         전용면적 60㎡이하  2015  10    5652
2  Seoul   전용면적 60㎡초과 85㎡이하  2015  10    5882
3  Seoul  전용면적 85㎡초과 102㎡이하  2015  10    5721
4  Seoul        전용면적 102㎡초과  2015  10    5879

In [26]:
new_index = [0, 1, 'a']
df1 = df.reindex([0, 1, 'a'])
df1

지역명        규모구분      연도     월 분양가격(㎡)
0  Seoul          전체  2015.0  10.0    5841
1  Seoul  전용면적 60㎡이하  2015.0  10.0    5652
a    NaN         NaN     NaN   NaN     NaN

In [25]:
df1.reindex(new_index, fill_value=3)

지역명        규모구분      연도     월 분양가격(㎡)
0  Seoul          전체  2015.0  10.0    5841
1  Seoul  전용면적 60㎡이하  2015.0  10.0    5652
a    NaN         NaN     NaN   NaN     NaN

In [33]:
df1 = df.reindex(index=df.index[:7], columns=list(df.columns) + ['extra'])
df1

지역명               규모구분    연도   월 분양가격(㎡)  extra
0  Seoul                 전체  2015  10    5841    NaN
1  Seoul         전용면적 60㎡이하  2015  10    5652    NaN
2  Seoul   전용면적 60㎡초과 85㎡이하  2015  10    5882    NaN
3  Seoul  전용면적 85㎡초과 102㎡이하  2015  10    5721    NaN
4  Seoul        전용면적 102㎡초과  2015  10    5879    NaN
5     인천                 전체  2015  10    3163    NaN
6     인천         전용면적 60㎡이하  2015  10    3488    NaN

In [39]:
df1.loc[:4, 'extra'] = 3
df1

지역명               규모구분    연도   월 분양가격(㎡) extra
0  Seoul                 전체  2015  10    5841     3
1  Seoul         전용면적 60㎡이하  2015  10    5652     3
2  Seoul   전용면적 60㎡초과 85㎡이하  2015  10    5882     3
3  Seoul  전용면적 85㎡초과 102㎡이하  2015  10    5721     3
4  Seoul        전용면적 102㎡초과  2015  10    5879     3
5     인천                 전체  2015  10    3163   NaN
6     인천         전용면적 60㎡이하  2015  10    3488   NaN

In [40]:
df2 = df1.copy()
df2

지역명               규모구분    연도   월 분양가격(㎡) extra
0  Seoul                 전체  2015  10    5841     3
1  Seoul         전용면적 60㎡이하  2015  10    5652     3
2  Seoul   전용면적 60㎡초과 85㎡이하  2015  10    5882     3
3  Seoul  전용면적 85㎡초과 102㎡이하  2015  10    5721     3
4  Seoul        전용면적 102㎡초과  2015  10    5879     3
5     인천                 전체  2015  10    3163   NaN
6     인천         전용면적 60㎡이하  2015  10    3488   NaN

In [44]:
df2.dropna(how='any')

지역명               규모구분    연도   월 분양가격(㎡) extra
0  Seoul                 전체  2015  10    5841     3
1  Seoul         전용면적 60㎡이하  2015  10    5652     3
2  Seoul   전용면적 60㎡초과 85㎡이하  2015  10    5882     3
3  Seoul  전용면적 85㎡초과 102㎡이하  2015  10    5721     3
4  Seoul        전용면적 102㎡초과  2015  10    5879     3

In [45]:
df2

지역명               규모구분    연도   월 분양가격(㎡) extra
0  Seoul                 전체  2015  10    5841     3
1  Seoul         전용면적 60㎡이하  2015  10    5652     3
2  Seoul   전용면적 60㎡초과 85㎡이하  2015  10    5882     3
3  Seoul  전용면적 85㎡초과 102㎡이하  2015  10    5721     3
4  Seoul        전용면적 102㎡초과  2015  10    5879     3
5     인천                 전체  2015  10    3163   NaN
6     인천         전용면적 60㎡이하  2015  10    3488   NaN

In [46]:
df2.dropna(how='any', inplace=True)

In [47]:
df2

지역명               규모구분    연도   월 분양가격(㎡) extra
0  Seoul                 전체  2015  10    5841     3
1  Seoul         전용면적 60㎡이하  2015  10    5652     3
2  Seoul   전용면적 60㎡초과 85㎡이하  2015  10    5882     3
3  Seoul  전용면적 85㎡초과 102㎡이하  2015  10    5721     3
4  Seoul        전용면적 102㎡초과  2015  10    5879     3

In [54]:
df2 = df1.copy()
df2

지역명               규모구분    연도   월 분양가격(㎡) extra
0  Seoul                 전체  2015  10    5841     3
1  Seoul         전용면적 60㎡이하  2015  10    5652     3
2  Seoul   전용면적 60㎡초과 85㎡이하  2015  10    5882     3
3  Seoul  전용면적 85㎡초과 102㎡이하  2015  10    5721     3
4  Seoul        전용면적 102㎡초과  2015  10    5879     3
5     인천                 전체  2015  10    3163   NaN
6     인천         전용면적 60㎡이하  2015  10    3488   NaN

In [52]:
df2.fillna(value='a')

지역명               규모구분    연도   월 분양가격(㎡) extra
0  Seoul                 전체  2015  10    5841     3
1  Seoul         전용면적 60㎡이하  2015  10    5652     3
2  Seoul   전용면적 60㎡초과 85㎡이하  2015  10    5882     3
3  Seoul  전용면적 85㎡초과 102㎡이하  2015  10    5721     3
4  Seoul        전용면적 102㎡초과  2015  10    5879     3
5     인천                 전체  2015  10    3163     a
6     인천         전용면적 60㎡이하  2015  10    3488     a

# **3. NaN 값이 있는 데이터를 Boolean 값으로 출력**

In [55]:
pd.isna(df2) #none인지 아닌지를 판별

지역명   규모구분     연도      월  분양가격(㎡)  extra
0  False  False  False  False    False  False
1  False  False  False  False    False  False
2  False  False  False  False    False  False
3  False  False  False  False    False  False
4  False  False  False  False    False  False
5  False  False  False  False    False   True
6  False  False  False  False    False   True

# **연산**

In [56]:
df.head()

지역명               규모구분    연도   월 분양가격(㎡)
0  Seoul                 전체  2015  10    5841
1  Seoul         전용면적 60㎡이하  2015  10    5652
2  Seoul   전용면적 60㎡초과 85㎡이하  2015  10    5882
3  Seoul  전용면적 85㎡초과 102㎡이하  2015  10    5721
4  Seoul        전용면적 102㎡초과  2015  10    5879

In [62]:
df.mean() #분양가는 none이 있어서 평균

연도    2017.5
월        6.5
dtype: float64

In [60]:
df.mean(1)[:5] #행(row) 기준 평균

0    1012.5
1    1012.5
2    1012.5
3    1012.5
4    1012.5
dtype: float64

In [63]:
df.mean(0)  #0이 열(column) 기준 평균

연도    2017.5
월        6.5
dtype: float64

In [64]:
df.head()

지역명               규모구분    연도   월 분양가격(㎡)
0  Seoul                 전체  2015  10    5841
1  Seoul         전용면적 60㎡이하  2015  10    5652
2  Seoul   전용면적 60㎡초과 85㎡이하  2015  10    5882
3  Seoul  전용면적 85㎡초과 102㎡이하  2015  10    5721
4  Seoul        전용면적 102㎡초과  2015  10    5879

행을 2칸 뒤로 밀기

In [65]:
df.shift(2)[:5]

지역명              규모구분      연도     월 분양가격(㎡)
0    NaN               NaN     NaN   NaN     NaN
1    NaN               NaN     NaN   NaN     NaN
2  Seoul                전체  2015.0  10.0    5841
3  Seoul        전용면적 60㎡이하  2015.0  10.0    5652
4  Seoul  전용면적 60㎡초과 85㎡이하  2015.0  10.0    5882

In [66]:
df.shift(-2)[:5]

지역명               규모구분      연도     월 분양가격(㎡)
0  Seoul   전용면적 60㎡초과 85㎡이하  2015.0  10.0    5882
1  Seoul  전용면적 85㎡초과 102㎡이하  2015.0  10.0    5721
2  Seoul        전용면적 102㎡초과  2015.0  10.0    5879
3     인천                 전체  2015.0  10.0    3163
4     인천         전용면적 60㎡이하  2015.0  10.0    3488

## Broadcasting을 이용한 subtract (빼기)

In [74]:
df1 = df[['연도', '월']]
df1.head()

연도   월
0  2015  10
1  2015  10
2  2015  10
3  2015  10
4  2015  10

In [75]:
df1.shape #(row, column)

(4590, 2)

In [72]:
s = np.ones(df.shape[0]) 
s.shape

(4590,)

In [73]:
s

array([1., 1., 1., ..., 1., 1., 1.])

In [77]:
df.shape[0]

4590

In [78]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

np.ones 를 하면 모든 원소를 1, zero 를 하면 0

np.ones(숫자)  -> 숫자만큼 1을 넣은 array를 만든다.

In [80]:
s

array([1., 1., 1., ..., 1., 1., 1.])

In [84]:
df1.sub(s*2, axis=0).head() #모든 데이터에서 다 빼기
#axis가 0이면 위에서 밑으로

연도    월
0  2013.0  8.0
1  2013.0  8.0
2  2013.0  8.0
3  2013.0  8.0
4  2013.0  8.0

In [85]:
s = np.ones(df1.shape[1])

In [86]:
s

array([1., 1.])

In [87]:
df1.sub(s, axis=1).head()

연도    월
0  2014.0  9.0
1  2014.0  9.0
2  2014.0  9.0
3  2014.0  9.0
4  2014.0  9.0

## Apply

In [96]:
df1.apply(np.cumsum)[50:]

연도      월
50     102765    510
51     104780    520
52     106795    530
53     108810    540
54     110825    550
...       ...    ...
4585  9252245  29823
4586  9254265  29826
4587  9256285  29829
4588  9258305  29832
4589  9260325  29835

[4540 rows x 2 columns]

In [98]:
df1

연도   월
0     2015  10
1     2015  10
2     2015  10
3     2015  10
4     2015  10
...    ...  ..
4585  2020   3
4586  2020   3
4587  2020   3
4588  2020   3
4589  2020   3

[4590 rows x 2 columns]

In [ ]:
df1.apply(np.cumsum)[:10] #apply : 모든 셀에 동일 함수 적용

In [97]:
df1.apply(lambda x: x.max() - x.min()) #x.max() 는 최대값인 12 x.min() 은 최소값인 1 12 - 1 = 11이 출력

연도     5
월     11
dtype: int64

In [99]:
df['규모구분'].value_counts()

전용면적 60㎡이하           918
전체                   918
전용면적 60㎡초과 85㎡이하     918
전용면적 85㎡초과 102㎡이하    918
전용면적 102㎡초과          918
Name: 규모구분, dtype: int64

In [100]:
df['연도'].value_counts()

2019    1020
2018    1020
2017    1020
2016    1020
2015     255
2020     255
Name: 연도, dtype: int64

In [101]:
df['지역명'].value_counts()

대구       270
Seoul    270
울산       270
인천       270
충북       270
광주       270
경남       270
경북       270
경기       270
대전       270
전북       270
세종       270
강원       270
전남       270
제주       270
충남       270
부산       270
Name: 지역명, dtype: int64